package com.mobilemcp.pro.security

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Persists the pairing secret, wrapped by a hardware-backed key where the device provides
 * one.
 *
 * The secret is never written to disk in the clear. A non-exportable AES-256 key lives in
 * the `AndroidKeyStore`; on devices with a secure element or TEE that key material never
 * enters the application process at all, so an attacker with a copy of the app's data
 * directory — an ADB backup, a stolen unencrypted image, another app exploiting a path
 * traversal — gets a ciphertext they cannot unwrap off-device.
 *
 * `SharedPreferences` rather than DataStore is a deliberate, narrow choice: this is a
 * single small blob read once when the server starts. DataStore's asynchronous API earns
 * its keep for frequent or large writes, and adds a dependency and a coroutine boundary
 * that buy nothing for one value read at startup.
 */
class PairingSecretStore(context: Context) {

    private val prefs: SharedPreferences =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    /**
     * Returns the stored secret, generating and persisting one on first use.
     *
     * If the wrapped blob cannot be decrypted — which happens legitimately when the user
     * adds a screen lock, restores a backup onto new hardware, or the Keystore key is
     * invalidated — a fresh secret is generated rather than leaving the server unusable.
     * The old secret becomes invalid at that point, so any paired client must re-pair.
     * That is the correct failure direction: re-pairing is an inconvenience, running
     * without a working secret is a security hole.
     */
    @Synchronized
    fun getOrCreate(): ByteArray {
        readSecret()?.let { return it }
        return SecureChannel.randomSecret().also(::writeSecret)
    }

    /** Replaces the secret. Every paired client must re-pair afterwards. */
    @Synchronized
    fun regenerate(): ByteArray = SecureChannel.randomSecret().also(::writeSecret)

    private fun readSecret(): ByteArray? {
        val stored = prefs.getString(KEY_WRAPPED_SECRET, null) ?: return null
        return try {
            val blob = android.util.Base64.decode(stored, android.util.Base64.NO_WRAP)
            if (blob.size <= GCM_IV_BYTES) return null

            val iv = blob.copyOfRange(0, GCM_IV_BYTES)
            val cipherText = blob.copyOfRange(GCM_IV_BYTES, blob.size)

            Cipher.getInstance(TRANSFORM).run {
                init(Cipher.DECRYPT_MODE, wrappingKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
                doFinal(cipherText)
            }.takeIf { it.size == SecureChannel.SECRET_BYTES }
        } catch (e: Exception) {
            // Never log the exception body: on some OEM Keystore implementations it can
            // echo key material. The type alone is enough to diagnose.
            Log.w(TAG, "Stored pairing secret unreadable (${e.javaClass.simpleName}); regenerating")
            null
        }
    }

    private fun writeSecret(secret: ByteArray) {
        // Randomised encryption is mandatory for AndroidKeyStore AES keys, so the IV is
        // generated by the Cipher and must be stored alongside the ciphertext.
        val cipher = Cipher.getInstance(TRANSFORM).apply {
            init(Cipher.ENCRYPT_MODE, wrappingKey())
        }
        val cipherText = cipher.doFinal(secret)
        val blob = ByteArray(cipher.iv.size + cipherText.size).also {
            cipher.iv.copyInto(it, 0)
            cipherText.copyInto(it, cipher.iv.size)
        }
        prefs.edit()
            .putString(KEY_WRAPPED_SECRET, android.util.Base64.encodeToString(blob, android.util.Base64.NO_WRAP))
            .apply()
    }

    private fun wrappingKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(256)
                    // Intentionally NOT setUserAuthenticationRequired: the server has to be
                    // able to start from a foreground service without the screen unlocked,
                    // which is the whole point of leaving it running.
                    .build()
            )
        }.generateKey()
    }

    private companion object {
        const val TAG = "PairingSecretStore"
        const val PREFS_NAME = "droidpilot_secure"
        const val KEY_WRAPPED_SECRET = "wrapped_pairing_secret"
        const val KEY_ALIAS = "droidpilot_secret_wrapping_key"
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val TRANSFORM = "AES/GCM/NoPadding"
        const val GCM_IV_BYTES = 12
        const val GCM_TAG_BITS = 128
    }
}
